use-auth-secret
static-auth-secret=turnsharedsecret
realm=meetflow.local
fingerprint
lt-cred-mech
listening-port=3478
tls-listening-port=5349
min-port=49160
max-port=49200
external-ip=127.0.0.1
no-cli
no-multicast-peers
no-tlsv1
no-tlsv1_1
log-file=stdout
simple-log
